{% set name = "resmda" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/resmda-{{ version }}.tar.gz
  sha256: 85a799a133e3bcdc58b290dee3657b158bc3a109cb2c68b6ddae2f164e8b3248

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - scipy
    - scooby

test:
  imports:
    - resmda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tuda-geo/resmda
  summary: A simple 2D reservoir modeller plus ESMDA.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://tuda-geo.github.io/resmda/

extra:
  recipe-maintainers:
    - prisae
    - gabrielserrao
